# Generated by Django 4.0.2 on 2022-03-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_number', models.AutoField(primary_key=True, serialize=False)),
                ('product_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_code', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('product_number', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_price', models.CharField(blank=True, max_length=15, null=True)),
                ('product_img', models.CharField(blank=True, max_length=50, null=True)),
                ('product_desc', models.TextField(blank=True, null=True)),
                ('product_desc_img', models.CharField(blank=True, max_length=50, null=True)),
                ('product_s_size', models.IntegerField(blank=True, null=True)),
                ('product_m_size', models.IntegerField(blank=True, null=True)),
                ('product_l_size', models.IntegerField(blank=True, null=True)),
                ('product_xl_size', models.IntegerField(blank=True, null=True)),
                ('product_hits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemQna',
            fields=[
                ('qna_number', models.AutoField(primary_key=True, serialize=False)),
                ('u_pwd', models.CharField(blank=True, max_length=50, null=True)),
                ('qna_title', models.CharField(blank=True, max_length=50, null=True)),
                ('qna_desc', models.TextField(blank=True, null=True)),
                ('qna_date', models.DateField(blank=True, null=True)),
                ('qna_state', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item_qna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainQna',
            fields=[
                ('m_qna_number', models.AutoField(primary_key=True, serialize=False)),
                ('u_pwd', models.CharField(blank=True, max_length=50, null=True)),
                ('m_qna_title', models.CharField(blank=True, max_length=50, null=True)),
                ('m_qna_desc', models.TextField(blank=True, null=True)),
                ('m_qna_date', models.DateField(blank=True, null=True)),
                ('m_qna_state', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_qna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order_detail_number', models.AutoField(primary_key=True, serialize=False)),
                ('order_detail_name', models.CharField(blank=True, max_length=20, null=True)),
                ('order_detail_address', models.CharField(blank=True, max_length=100, null=True)),
                ('order_detail_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'order_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderr',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('order_name', models.CharField(blank=True, max_length=20, null=True)),
                ('order_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('order_addr1', models.CharField(blank=True, max_length=100, null=True)),
                ('order_addr2', models.CharField(blank=True, max_length=100, null=True)),
                ('order_msg', models.TextField(blank=True, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_status', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'orderr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_number', models.AutoField(primary_key=True, serialize=False)),
                ('review_img', models.CharField(blank=True, max_length=50, null=True)),
                ('review_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_pwd', models.CharField(blank=True, max_length=50, null=True)),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user_email', models.CharField(blank=True, max_length=50, null=True)),
                ('user_address1', models.CharField(blank=True, max_length=100, null=True)),
                ('user_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('user_auth', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
