# Generated by Django 4.0.2 on 2022-03-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_number', models.AutoField(primary_key=True, serialize=False)),
                ('product_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_code', models.IntegerField(primary_key=True, serialize=False)),
                ('category_code2', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('product_number', models.AutoField(primary_key=True, serialize=False)),
                ('product_img', models.TextField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('product_desc', models.TextField(blank=True, null=True)),
                ('product_hits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order_detail_number', models.AutoField(primary_key=True, serialize=False)),
                ('order_detail_name', models.CharField(blank=True, max_length=20, null=True)),
                ('order_detail_address', models.CharField(blank=True, max_length=100, null=True)),
                ('order_detail_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'order_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderr',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_status', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'orderr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_pwd', models.CharField(blank=True, max_length=50, null=True)),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user_email', models.CharField(blank=True, max_length=50, null=True)),
                ('user_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
