# Generated by Django 4.0.2 on 2022-03-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_users_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemQna',
            fields=[
                ('qna_number', models.AutoField(primary_key=True, serialize=False)),
                ('u_pwd', models.CharField(blank=True, max_length=50, null=True)),
                ('qna_title', models.CharField(blank=True, max_length=50, null=True)),
                ('qna_desc', models.TextField(blank=True, null=True)),
                ('qna_date', models.DateField(blank=True, null=True)),
                ('qna_state', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item_qna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainQna',
            fields=[
                ('m_qna_number', models.AutoField(primary_key=True, serialize=False)),
                ('u_pwd', models.CharField(blank=True, max_length=50, null=True)),
                ('m_qna_title', models.CharField(blank=True, max_length=50, null=True)),
                ('m_qna_desc', models.TextField(blank=True, null=True)),
                ('m_qna_date', models.DateField(blank=True, null=True)),
                ('m_qna_state', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_qna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_number', models.AutoField(primary_key=True, serialize=False)),
                ('review_img', models.CharField(blank=True, max_length=50, null=True)),
                ('review_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
    ]
